webtalk_init -webtalk_dir /media/D/dong/HY3/3A/HY_3A/HY_3A.sdk/webtalk
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "2020-01-16 15:12:41" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "SDK v2018.3" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2018.3" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "amd64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "SDK" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "false" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "i52vbg50me480ktf3fshm8dvq" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2018.3_4" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "4" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Ubuntu" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Ubuntu 18.04.3 LTS" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Xeon(R) W-2155 CPU @ 3.30GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "1200.037 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "67.046 GB" -context "user_environment"
webtalk_register_client -client sdk
webtalk_add_data -client sdk -key uid -value "1579157214000" -context "sdk\\\\bsp/1579157214000"
webtalk_add_data -client sdk -key hwid -value "1579137615000" -context "sdk\\\\bsp/1579157214000"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\bsp/1579157214000"
webtalk_add_data -client sdk -key apptemplate -value "null" -context "sdk\\\\bsp/1579157214000"
webtalk_add_data -client sdk -key RecordType -value "BSPCreation" -context "sdk\\\\bsp/1579157214000"
webtalk_add_data -client sdk -key uid -value "1579157242000" -context "sdk\\\\application/1579157242000"
webtalk_add_data -client sdk -key hwid -value "1579137615000" -context "sdk\\\\application/1579157242000"
webtalk_add_data -client sdk -key bspid -value "1579157214000" -context "sdk\\\\application/1579157242000"
webtalk_add_data -client sdk -key newbsp -value "false" -context "sdk\\\\application/1579157242000"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\application/1579157242000"
webtalk_add_data -client sdk -key apptemplate -value "hello_world" -context "sdk\\\\application/1579157242000"
webtalk_add_data -client sdk -key RecordType -value "APPCreation" -context "sdk\\\\application/1579157242000"
webtalk_add_data -client sdk -key LangUsed -value "C" -context "sdk\\\\application/1579157242000"
webtalk_add_data -client sdk -key Procused -value "microblaze" -context "sdk\\\\application/1579157242000"
webtalk_add_data -client sdk -key projSize -value "362.41796875" -context "sdk\\\\application/1579157242000"
webtalk_add_data -client sdk -key uid -value "NA" -context "sdk\\\\bsp/1579158761118"
webtalk_add_data -client sdk -key RecordType -value "ToolUsage" -context "sdk\\\\bsp/1579158761118"
webtalk_add_data -client sdk -key BootgenCount -value "0" -context "sdk\\\\bsp/1579158761118"
webtalk_add_data -client sdk -key DebugCount -value "0" -context "sdk\\\\bsp/1579158761118"
webtalk_add_data -client sdk -key PerfCount -value "0" -context "sdk\\\\bsp/1579158761118"
webtalk_add_data -client sdk -key FlashCount -value "0" -context "sdk\\\\bsp/1579158761118"
webtalk_add_data -client sdk -key CrossTriggCount -value "0" -context "sdk\\\\bsp/1579158761118"
webtalk_add_data -client sdk -key QemuDebugCount -value "0" -context "sdk\\\\bsp/1579158761118"
webtalk_transmit -clientid 2381976000 -regid "" -xml /media/D/dong/HY3/3A/HY_3A/HY_3A.sdk/webtalk/usage_statistics_ext_sdk.xml -html /media/D/dong/HY3/3A/HY_3A/HY_3A.sdk/webtalk/usage_statistics_ext_sdk.html -wdm /media/D/dong/HY3/3A/HY_3A/HY_3A.sdk/webtalk/sdk_webtalk.wdm -intro "<H3>SDK Usage Report</H3><BR>"
webtalk_terminate
